apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uh5yigtdo-go 
  janus-idp.io/tekton: uh5yigtdo-go
  backstage.io/kubernetes-id: uh5yigtdo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uh5yigtdo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  